### ISSUE TITLE
Improve cooldown by removing the need for cooldown.update()

### ISSUE THREAD

**Issue by goldor8** [DarkRewar/BaseTool#59]
Calling cooldown.update() for each cooldown manually is kinda boilerplate. Instead, a CooldownManager could be added to the scene that keeps track of each cooldown and updates them automatically.

**Comment by DarkRewar** [comment]
Maybe could be an architecture based on a `CooldownManager` singleton, auto-instanced in DontDestroyOnLoad, where every cooldowns register themselves in constructor.

But, how do they unsubscribe? Because, using deconstructor or `IDisposable` interfaces only be used when the garbage collector gets them. If they are registered in another object, they will not be collected... So it will require a `Dispose()` call on `MonoBehaviour.OnDestroy` 🤔
